name             'apache'
maintainer       'Nobody'
maintainer_email 'nobody@example.com'
license          'all rights reserved'
description      'Installs/Configures apache'
version          '0.2.3'
